### ISSUE TITLE
Milestone for v3.0.0

### ISSUE THREAD

**Issue by kalpaj12** [kalpaj12/cookie-jar#12]
- [ ] Add extreme kill if site is doesn't view articles.
- [ ] Cleanup and refactor code
- [ ] Add support for other browsers
- [ ] Update master branch -> PR from dev
- [ ] Squash all commits and start clean?
